import { Puzzle } from './types'

export const PUZZLES: Puzzle[] = [
  // ===== 따내기 (입문) =====
  {
    id: 'capture-01',
    title: '돌 하나 잡기',
    description: '백돌 하나가 활로가 하나 남았습니다. 흑이 그 활로에 두어 백돌을 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[2,1],[3,2]],
      white: [[2,2]],
    },
    solution: [[2,3]],
    hint: [2,3],
    xpReward: 10,
  },
  {
    id: 'capture-02',
    title: '두 돌 잡기',
    description: '연결된 백돌 두 개를 잡으세요. 남은 활로가 하나입니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[1,3],[2,1],[3,2],[3,3]],
      white: [[2,2],[2,3]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 10,
  },
  {
    id: 'capture-03',
    title: '귀에서 잡기',
    description: '귀 쪽의 백돌을 잡으세요. 귀에서는 활로가 적어집니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,1],[1,2],[2,1]],
      white: [[0,0],[1,0],[1,1]],
    },
    solution: [[2,0]],
    hint: [2,0],
    xpReward: 10,
  },
  {
    id: 'capture-04',
    title: '변에서 잡기',
    description: '변 쪽 백돌 그룹을 잡으세요. 변에서는 활로가 2개 줄어듭니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[1,1],[1,3],[2,2]],
      white: [[0,1],[0,2],[1,2]],
    },
    solution: [[0,3]],
    hint: [0,3],
    xpReward: 15,
  },
  {
    id: 'capture-05',
    title: 'ㄱ자 모양 잡기',
    description: 'ㄱ자로 연결된 백돌 세 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,1],[2,0],[2,2],[3,0],[3,3],[4,2]],
      white: [[2,1],[3,1],[3,2]],
    },
    solution: [[4,1]],
    hint: [4,1],
    xpReward: 15,
  },

  // ===== 사활 - 살기 (입문) =====
  {
    id: 'live-01',
    title: '두 집 만들기 기초',
    description: '흑이 한 수를 두어 두 집을 만들어야 합니다. 가운데 어디에 두면 두 개의 독립된 공간이 생길까요?',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[0,4],[1,0],[1,1],[1,2],[1,3],[1,4]],
      white: [[0,5],[1,5],[2,0],[2,1],[2,2],[2,3],[2,4],[2,5]],
    },
    solution: [[0,2]],
    hint: [0,2],
    xpReward: 20,
  },
  {
    id: 'live-02',
    title: '변에서 살기 기초',
    description: '흑이 한 수를 두어 변 위에서 두 집을 만드세요. 가운데 어디에 두면 두 개의 독립된 공간이 생길까요?',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[4,0],[0,1],[1,1],[2,1],[3,1],[4,1]],
      white: [[0,2],[1,2],[2,2],[3,2],[4,2],[5,0],[5,1]],
    },
    solution: [[2,0]],
    hint: [2,0],
    xpReward: 20,
  },

  // ===== 따내기 (초급) =====
  {
    id: 'capture-06',
    title: '세 돌 한꺼번에 잡기',
    description: '변 위에 연결된 백돌 세 개를 잡으세요. 활로가 하나만 남아있습니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,3],[1,4],[1,5]],
      white: [[0,3],[0,4],[0,5]],
    },
    solution: [[0,6]],
    hint: [0,6],
    xpReward: 25,
  },
  {
    id: 'capture-07',
    title: '이단 잡기',
    description: '연결된 백돌 두 개의 마지막 활로를 막아 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,3],[2,4],[4,3],[4,4],[3,2]],
      white: [[3,3],[3,4]],
    },
    solution: [[3,5]],
    hint: [3,5],
    xpReward: 30,
  },
  {
    id: 'capture-08',
    title: 'ㄱ자 네 돌 잡기',
    description: 'ㄱ자 모양으로 연결된 백돌 네 개를 잡으세요. 활로가 하나 남았습니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[0,6],[1,3],[1,4],[2,5]],
      white: [[0,3],[0,4],[0,5],[1,5]],
    },
    solution: [[1,6]],
    hint: [1,6],
    xpReward: 25,
  },

  // ===== 사활 - 죽이기 (초급) =====
  {
    id: 'kill-01',
    title: '중앙 급소에 두기',
    description: '흑이 중앙 급소에 두어 백돌 두 개를 동시에 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,2],[3,3],[3,4],[4,1],[4,5],[5,2],[5,3],[5,4]],
      white: [[2,2],[2,3],[2,4],[4,2],[4,4],[6,2],[6,3],[6,4],[3,1],[5,1],[3,5],[5,5]],
    },
    solution: [[4,3]],
    hint: [4,3],
    xpReward: 30,
  },
  {
    id: 'kill-02',
    title: '급소에 두기',
    description: '백 그룹의 급소(핵심 위치)에 두어서 백을 죽이세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,2],[2,4],[3,3]],
      white: [[0,3],[1,2],[1,4],[2,3]],
    },
    solution: [[1,3]],
    hint: [1,3],
    xpReward: 30,
  },

  // ===== 사활 복합 (초급) =====
  {
    id: 'live-03',
    title: '귀에서 살기',
    description: '흑이 한 수를 두어 귀 근처에서 두 집을 만드세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,4],[0,8],[1,4],[1,5],[1,6],[1,7],[1,8]],
      white: [[0,3],[1,3],[2,4],[2,5],[2,6],[2,7],[2,8]],
    },
    solution: [[0,6]],
    hint: [0,6],
    xpReward: 25,
  },
  {
    id: 'capture-09',
    title: '양단수',
    description: '흑이 한 수를 두어 서로 떨어진 백돌 두 그룹을 동시에 단수에 몰아넣으세요. 백은 하나만 살릴 수 있습니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '양단수',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,2],[2,4],[4,2],[4,4]],
      white: [[3,2],[3,4]],
    },
    solution: [[3,3]],
    hint: [3,3],
    xpReward: 35,
  },
  {
    id: 'capture-10',
    title: 'ㄴ자 세 돌 잡기',
    description: 'ㄴ자 모양으로 연결된 백돌 세 개를 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[1,3],[2,1],[3,1],[3,3],[4,2]],
      white: [[2,2],[2,3],[3,2]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 35,
  },

  // ===== 중급 =====
  {
    id: 'live-04',
    title: '중앙에서 두 집 만들기',
    description: '흑이 한 수를 두어 중앙에서 두 집을 만드세요. 급소가 어디일까요?',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,2],[3,6],[4,2],[4,3],[4,4],[4,5],[4,6]],
      white: [[2,2],[2,3],[2,4],[2,5],[2,6],[3,1],[3,7],[4,1],[4,7],[5,2],[5,3],[5,4],[5,5],[5,6]],
    },
    solution: [[3,4]],
    hint: [3,4],
    xpReward: 50,
  },
  {
    id: 'kill-03',
    title: '급소 공격',
    description: '흑이 급소에 두어 두 개의 백돌을 잡으세요. 나머지 백돌도 위기에 빠집니다.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[2,1],[2,3],[4,1],[4,3],[5,2]],
      white: [[2,2],[3,1],[3,3],[4,2]],
    },
    solution: [[3,2]],
    hint: [3,2],
    xpReward: 50,
  },
  {
    id: 'capture-11',
    title: 'ㄴ자 다섯 돌 잡기',
    description: 'ㄴ자 모양으로 연결된 백돌 다섯 개를 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,3],[0,8],[1,4],[1,5],[1,6],[2,7]],
      white: [[0,4],[0,5],[0,6],[0,7],[1,7]],
    },
    solution: [[1,8]],
    hint: [1,8],
    xpReward: 45,
  },
  {
    id: 'live-05',
    title: '살기의 핵심 (급소)',
    description: '흑이 급소에 두어 두 집을 만드세요. 어떤 점이 두 집을 나누는 급소일까요?',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,3],[1,4],[1,5],[2,3],[2,5],[3,3],[3,5],[4,3],[4,5],[5,3],[5,4],[5,5]],
      white: [[0,3],[0,4],[0,5],[1,2],[1,6],[2,2],[2,6],[3,2],[3,6],[4,2],[4,6],[5,2],[5,6],[6,3],[6,4],[6,5]],
    },
    solution: [[3,4]],
    hint: [3,4],
    xpReward: 50,
  },
]

export const PUZZLES_BY_LEVEL = {
  beginner: PUZZLES.filter(p => p.level === 'beginner'),
  elementary: PUZZLES.filter(p => p.level === 'elementary'),
  intermediate: PUZZLES.filter(p => p.level === 'intermediate'),
}

export function getPuzzleById(id: string): Puzzle | undefined {
  return PUZZLES.find(p => p.id === id)
}
