import { Puzzle } from './types'

export const PUZZLES: Puzzle[] = [
  // ===== 따내기 (입문) =====
  {
    id: 'capture-01',
    title: '돌 하나 잡기',
    description: '백돌 하나가 활로가 하나 남았습니다. 흑이 그 활로에 두어 백돌을 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[2,1],[3,2]],
      white: [[2,2]],
    },
    solution: [[2,3]],
    hint: [2,3],
    xpReward: 10,
  },
  {
    id: 'capture-02',
    title: '두 돌 잡기',
    description: '연결된 백돌 두 개를 잡으세요. 남은 활로가 하나입니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[1,3],[2,1],[3,2],[3,3]],
      white: [[2,2],[2,3]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 10,
  },
  {
    id: 'capture-03',
    title: '귀에서 잡기',
    description: '귀 쪽의 백돌을 잡으세요. 귀에서는 활로가 적어집니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,1],[1,2],[2,1]],
      white: [[0,0],[1,0],[1,1]],
    },
    solution: [[2,0]],
    hint: [2,0],
    xpReward: 10,
  },
  {
    id: 'capture-04',
    title: '변에서 잡기',
    description: '변 쪽 백돌 그룹을 잡으세요. 변에서는 활로가 2개 줄어듭니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[1,1],[1,3],[2,2]],
      white: [[0,1],[0,2],[1,2]],
    },
    solution: [[0,3]],
    hint: [0,3],
    xpReward: 15,
  },
  {
    id: 'capture-05',
    title: 'ㄱ자 모양 잡기',
    description: 'ㄱ자로 연결된 백돌 세 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,1],[2,0],[2,2],[3,0],[3,3],[4,2]],
      white: [[2,1],[3,1],[3,2]],
    },
    solution: [[4,1]],
    hint: [4,1],
    xpReward: 15,
  },

  // ===== 사활 - 살기 (입문) =====
  {
    id: 'live-01',
    title: '두 집 만들기 기초',
    description: '흑이 한 수를 두어 두 집을 만들어야 합니다. 가운데 어디에 두면 두 개의 독립된 공간이 생길까요?',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[0,4],[1,0],[1,1],[1,2],[1,3],[1,4]],
      white: [[0,5],[1,5],[2,0],[2,1],[2,2],[2,3],[2,4],[2,5]],
    },
    solution: [[0,2]],
    hint: [0,2],
    xpReward: 20,
  },
  {
    id: 'live-02',
    title: '변에서 살기 기초',
    description: '흑이 한 수를 두어 변 위에서 두 집을 만드세요. 가운데 어디에 두면 두 개의 독립된 공간이 생길까요?',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[4,0],[0,1],[1,1],[2,1],[3,1],[4,1]],
      white: [[0,2],[1,2],[2,2],[3,2],[4,2],[5,0],[5,1]],
    },
    solution: [[2,0]],
    hint: [2,0],
    xpReward: 20,
  },

  // ===== 따내기 (초급) =====
  {
    id: 'capture-06',
    title: '세 돌 한꺼번에 잡기',
    description: '변 위에 연결된 백돌 세 개를 잡으세요. 활로가 하나만 남아있습니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,3],[1,4],[1,5]],
      white: [[0,3],[0,4],[0,5]],
    },
    solution: [[0,6]],
    hint: [0,6],
    xpReward: 25,
  },
  {
    id: 'capture-07',
    title: '이단 잡기',
    description: '연결된 백돌 두 개의 마지막 활로를 막아 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,3],[2,4],[4,3],[4,4],[3,2]],
      white: [[3,3],[3,4]],
    },
    solution: [[3,5]],
    hint: [3,5],
    xpReward: 30,
  },
  {
    id: 'capture-08',
    title: 'ㄱ자 네 돌 잡기',
    description: 'ㄱ자 모양으로 연결된 백돌 네 개를 잡으세요. 활로가 하나 남았습니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[0,6],[1,3],[1,4],[2,5]],
      white: [[0,3],[0,4],[0,5],[1,5]],
    },
    solution: [[1,6]],
    hint: [1,6],
    xpReward: 25,
  },

  // ===== 사활 - 죽이기 (초급) =====
  {
    id: 'kill-01',
    title: '중앙 급소에 두기',
    description: '흑이 중앙 급소에 두어 백돌 두 개를 동시에 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,2],[3,3],[3,4],[4,1],[4,5],[5,2],[5,3],[5,4]],
      white: [[2,2],[2,3],[2,4],[4,2],[4,4],[6,2],[6,3],[6,4],[3,1],[5,1],[3,5],[5,5]],
    },
    solution: [[4,3]],
    hint: [4,3],
    xpReward: 30,
  },
  {
    id: 'kill-02',
    title: '급소에 두기',
    description: '백 그룹의 급소(핵심 위치)에 두어서 백을 죽이세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,2],[2,4],[3,3]],
      white: [[0,3],[1,2],[1,4],[2,3]],
    },
    solution: [[1,3]],
    hint: [1,3],
    xpReward: 30,
  },

  // ===== 사활 복합 (초급) =====
  {
    id: 'live-03',
    title: '귀에서 살기',
    description: '흑이 한 수를 두어 귀 근처에서 두 집을 만드세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,4],[0,8],[1,4],[1,5],[1,6],[1,7],[1,8]],
      white: [[0,3],[1,3],[2,4],[2,5],[2,6],[2,7],[2,8]],
    },
    solution: [[0,6]],
    hint: [0,6],
    xpReward: 25,
  },
  {
    id: 'capture-09',
    title: '양단수',
    description: '흑이 한 수를 두어 서로 떨어진 백돌 두 그룹을 동시에 단수에 몰아넣으세요. 백은 하나만 살릴 수 있습니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '양단수',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,2],[2,4],[4,2],[4,4]],
      white: [[3,2],[3,4]],
    },
    solution: [[3,3]],
    hint: [3,3],
    xpReward: 35,
  },
  {
    id: 'capture-10',
    title: 'ㄴ자 세 돌 잡기',
    description: 'ㄴ자 모양으로 연결된 백돌 세 개를 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[1,3],[2,1],[3,1],[3,3],[4,2]],
      white: [[2,2],[2,3],[3,2]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 35,
  },

  // ===== 중급 =====
  {
    id: 'live-04',
    title: '중앙에서 두 집 만들기',
    description: '흑이 한 수를 두어 중앙에서 두 집을 만드세요. 급소가 어디일까요?',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,2],[3,6],[4,2],[4,3],[4,4],[4,5],[4,6]],
      white: [[2,2],[2,3],[2,4],[2,5],[2,6],[3,1],[3,7],[4,1],[4,7],[5,2],[5,3],[5,4],[5,5],[5,6]],
    },
    solution: [[3,4]],
    hint: [3,4],
    xpReward: 50,
  },
  {
    id: 'kill-03',
    title: '급소 공격',
    description: '흑이 급소에 두어 두 개의 백돌을 잡으세요. 나머지 백돌도 위기에 빠집니다.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[2,1],[2,3],[4,1],[4,3],[5,2]],
      white: [[2,2],[3,1],[3,3],[4,2]],
    },
    solution: [[3,2]],
    hint: [3,2],
    xpReward: 50,
  },
  {
    id: 'capture-11',
    title: 'ㄴ자 다섯 돌 잡기',
    description: 'ㄴ자 모양으로 연결된 백돌 다섯 개를 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,3],[0,8],[1,4],[1,5],[1,6],[2,7]],
      white: [[0,4],[0,5],[0,6],[0,7],[1,7]],
    },
    solution: [[1,8]],
    hint: [1,8],
    xpReward: 45,
  },
  {
    id: 'live-05',
    title: '살기의 핵심 (급소)',
    description: '흑이 급소에 두어 두 집을 만드세요. 어떤 점이 두 집을 나누는 급소일까요?',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,3],[1,4],[1,5],[2,3],[2,5],[3,3],[3,5],[4,3],[4,5],[5,3],[5,4],[5,5]],
      white: [[0,3],[0,4],[0,5],[1,2],[1,6],[2,2],[2,6],[3,2],[3,6],[4,2],[4,6],[5,2],[5,6],[6,3],[6,4],[6,5]],
    },
    solution: [[3,4]],
    hint: [3,4],
    xpReward: 50,
  },

  // ===== 입문 따내기 추가 =====
  {
    id: 'capture-12',
    title: '변 돌 하나 잡기',
    description: '변에 있는 백돌 하나를 잡으세요. 남은 활로를 막으면 됩니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[1,1]],
      white: [[0,1]],
    },
    solution: [[0,2]],
    hint: [0,2],
    xpReward: 10,
  },
  {
    id: 'capture-13',
    title: '중앙 단수',
    description: '중앙의 백돌 하나를 잡으세요. 마지막 활로에 두면 됩니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,4],[4,3],[4,5]],
      white: [[4,4]],
    },
    solution: [[5,4]],
    hint: [5,4],
    xpReward: 10,
  },
  {
    id: 'capture-14',
    title: '귀 두 돌 잡기',
    description: '귀에 있는 백돌 두 개를 잡으세요. 활로가 하나 남았습니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,1],[2,0]],
      white: [[0,0],[1,0]],
    },
    solution: [[1,1]],
    hint: [1,1],
    xpReward: 10,
  },
  {
    id: 'capture-15',
    title: '변 두 돌 잡기',
    description: '변에 있는 백돌 두 개를 잡으세요. 남은 활로에 두세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,3],[1,4]],
      white: [[0,3],[0,4]],
    },
    solution: [[0,5]],
    hint: [0,5],
    xpReward: 10,
  },
  {
    id: 'capture-16',
    title: '변 세 돌 직선 잡기',
    description: '변 위에 직선으로 놓인 백돌 세 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[1,1],[1,2],[1,3]],
      white: [[0,1],[0,2],[0,3]],
    },
    solution: [[0,4]],
    hint: [0,4],
    xpReward: 15,
  },
  {
    id: 'capture-17',
    title: '귀 ㄱ자 세 돌 잡기',
    description: '귀에서 ㄱ자로 연결된 백돌 세 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,0],[2,1]],
      white: [[0,0],[0,1],[1,1]],
    },
    solution: [[1,2]],
    hint: [1,2],
    xpReward: 15,
  },
  {
    id: 'capture-18',
    title: '변 ㄴ자 세 돌 잡기',
    description: '변에서 ㄴ자로 연결된 백돌 세 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,4],[0,7],[1,5],[2,6]],
      white: [[0,5],[0,6],[1,6]],
    },
    solution: [[1,7]],
    hint: [1,7],
    xpReward: 15,
  },
  {
    id: 'capture-19',
    title: '중앙 세 돌 묶어 잡기',
    description: '중앙에서 연결된 백돌 세 개를 잡으세요. 유일한 활로를 막으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,3],[2,4],[3,2],[3,5],[4,2],[4,5],[5,3],[5,4]],
      white: [[3,3],[3,4],[4,3]],
    },
    solution: [[4,4]],
    hint: [4,4],
    xpReward: 15,
  },
  {
    id: 'capture-20',
    title: '우하귀 두 돌 잡기',
    description: '우하귀의 백돌 두 개를 잡으세요. 활로가 하나 남았습니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[7,8],[8,6]],
      white: [[8,7],[8,8]],
    },
    solution: [[7,7]],
    hint: [7,7],
    xpReward: 10,
  },
  {
    id: 'capture-21',
    title: '귀 세 돌 잡기',
    description: '귀에 있는 백돌 세 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,1]],
      white: [[0,0],[0,1],[1,0]],
    },
    solution: [[2,0]],
    hint: [2,0],
    xpReward: 15,
  },
  {
    id: 'capture-22',
    title: 'S자 네 돌 잡기',
    description: 'S자 모양으로 연결된 백돌 네 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,1],[1,3],[2,1],[3,2],[3,4],[4,3]],
      white: [[1,2],[2,2],[2,3],[3,3]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 15,
  },
  {
    id: 'capture-23',
    title: '변 부채꼴 잡기',
    description: '변에서 부채꼴 모양 백돌 네 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[0,6],[1,3],[1,5]],
      white: [[0,3],[0,4],[0,5],[1,4]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 15,
  },
  {
    id: 'capture-24',
    title: '변 네 돌 직선 잡기',
    description: '변 위에 직선으로 놓인 백돌 네 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[1,1],[1,2],[1,3],[1,4]],
      white: [[0,1],[0,2],[0,3],[0,4]],
    },
    solution: [[0,5]],
    hint: [0,5],
    xpReward: 15,
  },
  {
    id: 'capture-25',
    title: '귀 네 돌 ㄱ자 잡기',
    description: '귀에서 ㄱ자로 연결된 백돌 네 개를 잡으세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,3],[1,0],[1,1],[2,2]],
      white: [[0,0],[0,1],[0,2],[1,2]],
    },
    solution: [[1,3]],
    hint: [1,3],
    xpReward: 15,
  },

  // ===== 입문 살기 추가 =====
  {
    id: 'live-06',
    title: '변 가로 살기',
    description: '흑이 가운데에 두어 두 집을 만드세요. 양쪽에 독립된 공간이 생깁니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[4,2],[4,6],[5,2],[5,3],[5,4],[5,5],[5,6]],
      white: [[3,2],[3,3],[3,4],[3,5],[3,6],[4,1],[4,7],[5,1],[5,7],[6,2],[6,3],[6,4],[6,5],[6,6]],
    },
    solution: [[4,4]],
    hint: [4,4],
    xpReward: 20,
  },
  {
    id: 'live-07',
    title: '변 세로 살기',
    description: '흑이 가운데에 두어 세로로 두 집을 만드세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,6],[6,6],[3,6],[4,6],[5,6],[2,7],[6,7]],
      white: [[1,6],[1,7],[2,5],[3,5],[4,5],[5,5],[6,5],[7,6],[7,7],[2,8],[6,8]],
    },
    solution: [[4,7]],
    hint: [4,7],
    xpReward: 20,
  },
  {
    id: 'live-08',
    title: '귀 가로 살기',
    description: '우하귀에서 흑이 한 수를 두어 두 집을 만드세요.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[7,4],[7,8],[8,4],[8,5],[8,6],[8,7],[8,8]],
      white: [[6,4],[6,5],[6,6],[6,7],[6,8],[7,3],[8,3]],
    },
    solution: [[7,6]],
    hint: [7,6],
    xpReward: 20,
  },
  {
    id: 'live-09',
    title: '변 세로 살기 2',
    description: '변에서 세로로 두 집을 만드세요. 급소는 가운데입니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[4,2],[1,2],[2,2],[3,2],[0,3],[4,3]],
      white: [[0,1],[1,1],[2,1],[3,1],[4,1],[5,2],[5,3],[0,4],[1,4],[2,4],[3,4],[4,4]],
    },
    solution: [[2,3]],
    hint: [2,3],
    xpReward: 20,
  },
  {
    id: 'live-10',
    title: '변 긴 살기',
    description: '변에서 흑이 한 수를 두어 두 집을 만드세요. 가운데가 급소입니다.',
    level: 'beginner',
    levelLabel: '입문',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[7,1],[7,5],[8,1],[8,2],[8,3],[8,4],[8,5]],
      white: [[6,1],[6,2],[6,3],[6,4],[6,5],[7,0],[7,6],[8,0],[8,6]],
    },
    solution: [[7,3]],
    hint: [7,3],
    xpReward: 20,
  },

  // ===== 초급 따내기 추가 =====
  {
    id: 'capture-26',
    title: '대마 잡기',
    description: '여러 개로 연결된 백 대마를 잡으세요. 유일한 활로를 막으면 됩니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,3],[2,4],[2,5],[3,2],[3,6],[4,2],[4,6],[5,3],[5,5]],
      white: [[3,3],[3,4],[3,5],[4,3],[4,4],[4,5]],
    },
    solution: [[5,4]],
    hint: [5,4],
    xpReward: 40,
  },
  {
    id: 'capture-27',
    title: '대각 꺾임 잡기',
    description: '대각선으로 꺾인 백돌 그룹을 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,1],[2,0],[2,2],[3,0],[3,3],[4,1],[4,4],[5,3]],
      white: [[2,1],[3,1],[3,2],[4,2],[4,3]],
    },
    solution: [[5,2]],
    hint: [5,2],
    xpReward: 35,
  },
  {
    id: 'capture-28',
    title: 'Z형 잡기',
    description: 'Z자 모양의 백돌 그룹을 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,4],[1,3],[1,5],[2,3],[3,4],[3,6],[4,5]],
      white: [[1,4],[2,4],[2,5],[3,5]],
    },
    solution: [[2,6]],
    hint: [2,6],
    xpReward: 30,
  },
  {
    id: 'capture-29',
    title: '귀 복잡 잡기',
    description: '귀에서 복잡하게 연결된 백돌을 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,1],[0,3],[1,1],[2,2],[2,4],[3,3]],
      white: [[0,2],[1,2],[1,3],[2,3]],
    },
    solution: [[1,4]],
    hint: [1,4],
    xpReward: 30,
  },
  {
    id: 'capture-30',
    title: '변 긴 뱀 잡기',
    description: '변을 따라 길게 연결된 백돌 뱀을 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[0,5],[1,0],[1,1],[1,2],[1,3],[1,5],[2,1],[2,5],[3,3],[3,4]],
      white: [[0,1],[0,2],[0,3],[0,4],[1,4],[2,4],[2,3],[2,2]],
    },
    solution: [[3,2]],
    hint: [3,2],
    xpReward: 35,
  },
  {
    id: 'capture-31',
    title: '양단수 2',
    description: '한 수로 떨어진 백돌 두 개를 동시에 단수에 넣으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,3],[2,2],[2,4],[3,2],[3,4],[4,2],[4,4],[5,3]],
      white: [[2,3],[4,3]],
    },
    solution: [[3,3]],
    hint: [3,3],
    xpReward: 35,
  },
  {
    id: 'capture-32',
    title: '중앙 십자 잡기',
    description: '중앙의 십자 모양 백돌 그룹을 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,3],[3,5],[4,2],[4,6],[5,3],[5,5],[6,4]],
      white: [[3,4],[4,3],[4,4],[4,5],[5,4]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 35,
  },
  {
    id: 'capture-33',
    title: '변 ㄷ자 잡기',
    description: '변에서 ㄷ자로 연결된 백돌을 잡으세요. 급소를 찾으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[0,6],[1,2],[1,6],[2,3],[2,4],[2,5]],
      white: [[0,3],[0,4],[0,5],[1,3],[1,5]],
    },
    solution: [[1,4]],
    hint: [1,4],
    xpReward: 35,
  },
  {
    id: 'capture-34',
    title: '초급 귀 양단수',
    description: '한 수로 귀 근처의 백돌 두 개를 동시에 단수에 넣으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,0],[0,2],[1,3],[2,0],[2,2]],
      white: [[1,0],[1,2]],
    },
    solution: [[1,1]],
    hint: [1,1],
    xpReward: 35,
  },
  {
    id: 'capture-35',
    title: '변 다섯 돌 직선 잡기',
    description: '변에서 직선으로 연결된 백돌 다섯 개를 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,1],[1,2],[1,3],[1,4],[1,5],[1,6]],
      white: [[0,2],[0,3],[0,4],[0,5],[0,6]],
    },
    solution: [[0,7]],
    hint: [0,7],
    xpReward: 30,
  },

  // ===== 초급 죽이기 추가 =====
  {
    id: 'kill-04',
    title: '꽉 막힌 급소',
    description: '흑이 급소에 두어 사방의 백돌을 동시에 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,2],[1,1],[1,3],[2,0],[2,4],[3,1],[3,3],[4,2]],
      white: [[1,2],[2,1],[2,3],[3,2]],
    },
    solution: [[2,2]],
    hint: [2,2],
    xpReward: 40,
  },
  {
    id: 'kill-05',
    title: '변 급소 따내기',
    description: '변에서 백돌 그룹의 마지막 활로를 막아 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,1],[0,4],[1,1],[1,2],[2,3]],
      white: [[0,2],[0,3],[1,3]],
    },
    solution: [[1,4]],
    hint: [1,4],
    xpReward: 30,
  },
  {
    id: 'kill-06',
    title: '단순 3돌 급소',
    description: '백돌 세 개의 유일한 활로를 막아 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,3],[2,2],[2,4],[3,2],[4,3],[4,4]],
      white: [[2,3],[3,3],[3,4]],
    },
    solution: [[3,5]],
    hint: [3,5],
    xpReward: 30,
  },
  {
    id: 'kill-07',
    title: '변 죽이기 급소',
    description: '변에서 백돌 그룹의 급소에 두어 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,3],[0,7],[1,4],[1,6]],
      white: [[0,4],[0,5],[0,6],[1,5]],
    },
    solution: [[2,5]],
    hint: [2,5],
    xpReward: 30,
  },
  {
    id: 'kill-08',
    title: '대각 급소',
    description: '십자 모양 백돌의 유일한 활로를 막아 잡으세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,4],[3,3],[3,5],[4,2],[4,6],[5,3],[5,5]],
      white: [[3,4],[4,3],[4,4],[4,5],[5,4]],
    },
    solution: [[6,4]],
    hint: [6,4],
    xpReward: 40,
  },

  // ===== 초급 살기 추가 =====
  {
    id: 'live-11',
    title: '초급 살기 급소',
    description: '흑이 급소에 두어 두 집을 만드세요. 내부 공간을 둘로 나누세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,2],[2,6],[3,2],[3,3],[3,4],[3,5],[3,6],[4,2],[4,6]],
      white: [[1,2],[1,3],[1,4],[1,5],[1,6],[2,1],[2,7],[3,1],[3,7],[4,1],[4,7],[5,2],[5,3],[5,4],[5,5],[5,6]],
    },
    solution: [[2,4]],
    hint: [2,4],
    xpReward: 25,
  },
  {
    id: 'live-12',
    title: '귀 초급 살기',
    description: '좌하귀에서 흑이 급소에 두어 두 집을 만드세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[6,0],[6,4],[7,0],[7,1],[7,2],[7,3],[7,4]],
      white: [[5,0],[5,1],[5,2],[5,3],[5,4],[6,5],[7,5],[8,0],[8,1],[8,2],[8,3],[8,4]],
    },
    solution: [[6,2]],
    hint: [6,2],
    xpReward: 25,
  },
  {
    id: 'live-13',
    title: '중앙 사각 살기',
    description: '중앙에서 흑이 급소에 두어 두 집을 만드세요.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,3],[3,7],[4,3],[4,4],[4,5],[4,6],[4,7],[5,3],[5,7]],
      white: [[2,3],[2,4],[2,5],[2,6],[2,7],[3,2],[3,8],[4,2],[4,8],[5,2],[5,8],[6,3],[6,4],[6,5],[6,6],[6,7]],
    },
    solution: [[3,5]],
    hint: [3,5],
    xpReward: 30,
  },
  {
    id: 'live-14',
    title: '변 L자 살기',
    description: '변에서 L자 모양의 흑 그룹이 살려면 급소에 두어야 합니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[5,0],[5,4],[6,0],[6,1],[6,2],[6,3],[6,4],[7,4],[8,0],[8,4]],
      white: [[4,0],[4,1],[4,2],[4,3],[4,4],[5,5],[6,5],[7,0],[7,5],[8,1],[8,2],[8,3],[8,5]],
    },
    solution: [[5,2]],
    hint: [5,2],
    xpReward: 30,
  },
  {
    id: 'live-15',
    title: '변 가로 살기 (초급)',
    description: '변에서 가로로 두 집을 만드세요. 가운데가 급소입니다.',
    level: 'elementary',
    levelLabel: '초급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,1],[2,5],[3,1],[3,2],[3,3],[3,4],[3,5]],
      white: [[1,1],[1,2],[1,3],[1,4],[1,5],[2,0],[2,6],[3,0],[3,6],[4,1],[4,2],[4,3],[4,4],[4,5]],
    },
    solution: [[2,3]],
    hint: [2,3],
    xpReward: 25,
  },

  // ===== 중급 따내기 추가 =====
  {
    id: 'capture-36',
    title: '큰 그룹 단수 마무리',
    description: '큰 백 그룹의 유일한 활로를 막아 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,2],[1,3],[1,4],[2,1],[2,5],[3,1],[3,5],[4,1],[4,5],[5,3]],
      white: [[2,2],[2,3],[2,4],[3,2],[3,4],[4,2],[4,3],[4,4]],
    },
    solution: [[3,3]],
    hint: [3,3],
    xpReward: 45,
  },
  {
    id: 'capture-37',
    title: '중급 복잡 잡기',
    description: '사각형으로 연결된 백돌 네 개의 유일한 활로를 막으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[3,4],[3,5],[4,3],[4,6],[5,3],[5,6],[6,5]],
      white: [[4,4],[4,5],[5,4],[5,5]],
    },
    solution: [[6,4]],
    hint: [6,4],
    xpReward: 45,
  },
  {
    id: 'capture-38',
    title: '중급 연결 잡기',
    description: '대각선으로 연결된 백돌 그룹의 마지막 활로를 막으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,1],[1,2],[2,0],[2,3],[3,1],[3,4],[4,2],[4,4]],
      white: [[2,1],[2,2],[3,2],[3,3],[4,3]],
    },
    solution: [[5,3]],
    hint: [5,3],
    xpReward: 50,
  },
  {
    id: 'capture-39',
    title: '중급 대마 잡기',
    description: '큰 사각형 백 대마의 유일한 급소를 찾아 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[2,3],[2,4],[2,5],[3,2],[3,6],[4,2],[4,6],[5,2],[5,6],[6,3],[6,4]],
      white: [[3,3],[3,4],[3,5],[4,3],[4,5],[5,3],[5,4],[5,5]],
    },
    solution: [[4,4]],
    hint: [4,4],
    xpReward: 50,
  },
  {
    id: 'capture-40',
    title: '중급 귀 대마 잡기',
    description: '귀에서 큰 백 그룹의 마지막 활로를 찾아 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'capture',
    objectiveLabel: '따내기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,3],[1,1],[1,3],[3,0],[3,1],[3,2]],
      white: [[0,0],[0,1],[0,2],[1,0],[1,2],[2,0],[2,1],[2,2]],
    },
    solution: [[2,3]],
    hint: [2,3],
    xpReward: 50,
  },

  // ===== 중급 살기 추가 =====
  {
    id: 'live-16',
    title: '중급 긴 살기',
    description: '긴 내부 공간의 가운데에 두어 두 집을 만드세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[4,1],[4,2],[4,6],[4,7],[5,1],[5,2],[5,3],[5,4],[5,5],[5,6],[5,7]],
      white: [[3,1],[3,2],[3,3],[3,4],[3,5],[3,6],[3,7],[4,0],[4,8],[5,0],[5,8],[6,1],[6,2],[6,3],[6,4],[6,5],[6,6],[6,7]],
    },
    solution: [[4,4]],
    hint: [4,4],
    xpReward: 45,
  },
  {
    id: 'live-17',
    title: '중급 변 살기',
    description: '변에서 흑이 급소에 두어 두 집을 만드세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'live',
    objectiveLabel: '살기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[5,2],[5,6],[6,2],[6,3],[6,4],[6,5],[6,6],[7,2],[7,6]],
      white: [[4,2],[4,3],[4,4],[4,5],[4,6],[5,1],[5,7],[6,1],[6,7],[7,1],[7,7],[8,2],[8,3],[8,4],[8,5],[8,6]],
    },
    solution: [[5,4]],
    hint: [5,4],
    xpReward: 45,
  },

  // ===== 중급 죽이기 추가 =====
  {
    id: 'kill-09',
    title: '중급 십자 죽이기',
    description: '십자 모양 백돌 그룹의 유일한 활로를 막아 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[1,4],[2,3],[2,5],[3,2],[3,6],[4,3],[4,5]],
      white: [[2,4],[3,3],[3,4],[3,5],[4,4]],
    },
    solution: [[5,4]],
    hint: [5,4],
    xpReward: 50,
  },
  {
    id: 'kill-10',
    title: '중급 귀 죽이기',
    description: '귀에서 큰 백 그룹의 급소에 두어 잡으세요.',
    level: 'intermediate',
    levelLabel: '중급',
    objective: 'kill',
    objectiveLabel: '죽이기',
    turn: 'black',
    boardSize: 9,
    stones: {
      black: [[0,4],[1,4],[1,7],[1,8],[3,5],[3,6],[3,7],[3,8]],
      white: [[0,5],[0,6],[0,7],[0,8],[1,5],[2,5],[2,6],[2,7],[2,8]],
    },
    solution: [[1,6]],
    hint: [1,6],
    xpReward: 50,
  },
]

export const PUZZLES_BY_LEVEL = {
  beginner: PUZZLES.filter(p => p.level === 'beginner'),
  elementary: PUZZLES.filter(p => p.level === 'elementary'),
  intermediate: PUZZLES.filter(p => p.level === 'intermediate'),
}

export function getPuzzleById(id: string): Puzzle | undefined {
  return PUZZLES.find(p => p.id === id)
}
